== Catalog Info Generator

include::./includes/attributes.adoc[]

The extension provides the ability to generate the `catalog-info.yaml` file at build time or using the CLI.
More specifically, it generates `catalog-info.yaml` with the following content:

- Component matching the current project
- Optional API entries for the detected APIs
- Labels related to Kubernetes
- Annotations with SCM information
- Relations between API(s) and the Component(s)

This allows easy registration to Backstage but most importantly, it helps keeping the `catalog-info.yaml` up-to-date with the project's metadata.

=== Generating the catalog-info.yaml at build time

To generate the `catalog-info.yaml` at build time, add the `quarkus-backstage` extension to the project.

```xml
<dependency>
    <groupId>io.quarkiverse.backstage</groupId>
    <artifactId>quarkus-backstage</artifactId>
    <version>${quarkus-backstage.version}</version>
</dependency>
```

This feature is enabled out of the box and can be disabled using the following property:

[source,properties]
----
quarkus.backstage.catalog.generation.enabled=false
----

Alternatively, the extension can be added using the CLI:

[source,shell]
----
quarkus ext add quarkus-backstage
----

After adding the extension, the `catalog-info.yaml` will be generated on each build at the root of the project.

The feature is enabled by default and can be disabled using the following property:

[source,properties]
----
quarkus.backstage.catalog.generation.enabled=false
----

=== Generating the catalog-info.yaml using the CLI

The `catalog-info.yaml` can be generated using the CLI without requiring the extension to be added to the project.
This requires adding `quarkus-backstage` CLI plugin to the Quarkus CLI (see [Using the CLI](#using-the-cli)).

[sources,shell]
----
quarkus backstage entities generate
----

